apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 643968575852.dkr.ecr.eu-west-2.amazonaws.com/udacity-captsone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
